# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import feature_pb2 as feature__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in feature_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeatureServiceStub:
    """特征提取服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractFeatures = channel.unary_unary(
            '/feature.FeatureService/ExtractFeatures',
            request_serializer=feature__pb2.ExtractRequest.SerializeToString,
            response_deserializer=feature__pb2.ExtractReply.FromString,
            _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
            '/feature.FeatureService/GetModelInfo',
            request_serializer=feature__pb2.ModelInfoRequest.SerializeToString,
            response_deserializer=feature__pb2.ModelInfoReply.FromString,
            _registered_method=True)


class FeatureServiceServicer:
    """特征提取服务
    """

    def ExtractFeatures(self, request, context):
        """批量提取：输入一组图像（字节或 URL），返回特征向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """健康检查 / 模型信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ExtractFeatures': grpc.unary_unary_rpc_method_handler(
            servicer.ExtractFeatures,
            request_deserializer=feature__pb2.ExtractRequest.FromString,
            response_serializer=feature__pb2.ExtractReply.SerializeToString,
        ),
        'GetModelInfo': grpc.unary_unary_rpc_method_handler(
            servicer.GetModelInfo,
            request_deserializer=feature__pb2.ModelInfoRequest.FromString,
            response_serializer=feature__pb2.ModelInfoReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'feature.FeatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'feature.FeatureService', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class FeatureService:
    """特征提取服务
    """

    @staticmethod
    def ExtractFeatures(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feature.FeatureService/ExtractFeatures',
            feature__pb2.ExtractRequest.SerializeToString,
            feature__pb2.ExtractReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feature.FeatureService/GetModelInfo',
            feature__pb2.ModelInfoRequest.SerializeToString,
            feature__pb2.ModelInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
