# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'feature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfeature.proto\x12\x07\x66\x65\x61ture\"A\n\x0e\x45xtractRequest\x12\r\n\x05image\x18\x01 \x03(\x0c\x12\x11\n\timage_url\x18\x02 \x03(\t\x12\r\n\x05model\x18\x03 \x01(\t\"O\n\x0c\x45xtractReply\x12\x0b\n\x03\x64im\x18\x01 \x01(\r\x12\"\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\x10.feature.Feature\x12\x0e\n\x06\x65rrors\x18\x03 \x03(\t\"\x19\n\x07\x46\x65\x61ture\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"!\n\x10ModelInfoRequest\x12\r\n\x05model\x18\x01 \x01(\t\"<\n\x0eModelInfoReply\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0b\n\x03\x64im\x18\x02 \x01(\r\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t2\x97\x01\n\x0e\x46\x65\x61tureService\x12\x41\n\x0f\x45xtractFeatures\x12\x17.feature.ExtractRequest\x1a\x15.feature.ExtractReply\x12\x42\n\x0cGetModelInfo\x12\x19.feature.ModelInfoRequest\x1a\x17.feature.ModelInfoReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTREQUEST']._serialized_start=26
  _globals['_EXTRACTREQUEST']._serialized_end=91
  _globals['_EXTRACTREPLY']._serialized_start=93
  _globals['_EXTRACTREPLY']._serialized_end=172
  _globals['_FEATURE']._serialized_start=174
  _globals['_FEATURE']._serialized_end=199
  _globals['_MODELINFOREQUEST']._serialized_start=201
  _globals['_MODELINFOREQUEST']._serialized_end=234
  _globals['_MODELINFOREPLY']._serialized_start=236
  _globals['_MODELINFOREPLY']._serialized_end=296
  _globals['_FEATURESERVICE']._serialized_start=299
  _globals['_FEATURESERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
