apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-world
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
